# Generated by Django 3.1.5 on 2021-01-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('requests_number', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[('in the process', 1), ('proofreading', 2), ('published', 3)])),
                ('publishing_date', models.DateField()),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=288)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_created=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=300)),
                ('active_status', models.BooleanField(default=True)),
                ('writer', models.BooleanField(default=False)),
                ('interests', models.ManyToManyField(to='Blog_main.Interests')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('background_color', models.IntegerField()),
                ('public', models.BooleanField(default=False)),
                ('article', models.ManyToManyField(to='Blog_main.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog_main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog_main.user')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog_main.author'),
        ),
    ]
