# Generated by Django 3.1.5 on 2021-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_main', '0003_article_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background_color',
            field=models.IntegerField(default=1),
        ),
    ]
