# Generated by Django 3.1.5 on 2021-01-29 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog_main', '0005_auto_20210128_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
