# Generated by Django 3.1.5 on 2021-02-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_main', '0009_auto_20210130_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='picture',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
